import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";
import AppContext from "@/context";
import { Montserrat } from "next/font/google";
import "swiper/css";
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "CliniClick",
  description: "Generated by create next app",
};

import Login from "@/src/component/login/login";
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <AppContext>{children}</AppContext>
      </body>
    </html>
  );
}
