import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";
import { Montserrat } from "next/font/google";
import Footer from "@/src/component/footer/footer";
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <div className="container">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
